### ISSUE TITLE
API通信処理の追加

### ISSUE THREAD

**Issue by hiro-minami** [Omoitsuki/pairing-food-coffee#8]
# 概要
- 各画面遷移時にAPI通信処理を追加する
- useEffectを使って初期表示時にAPI通信を行い、レスポンスをStateに格納する

# 論点
- 状態管理をどうするか
  - 各画面ごとにAPIを叩く仕様であればStateで管理する方が楽な気がするが、ContextやReduxを使う手もある。メリデメを簡単に整理してどちらにするか決めておきたい。

**Comment by soysan** [comment]
コーヒー、フード、大陸とか扱うデータの型や大きさ違うのでもしかしたらReduxの方が良いのかも知れないですね。contextだと三つぐらいネストして実装しないといけないかもです。

**Comment by hiro-minami** [comment]
なるほどですね、となると今の所のメリデメとしては以下ですかね？
（個人的な見解として、今回は各ページでAPIを取得した後に状態が変わることはないと思っているので、各ページにState持たせて管理するのが一番楽かなと思っています。）
| 管理法 | メリット | デメリット |
| ------ | --------- | ----------- |
| State | 状態が変わらない場合、実装が楽 | API取得後に状態が変わる場合、管理が大変になる（現状API通信後に状態が変わることはないと思っているので特に大変になることはなさそう） |
| Context | 状態が変わる場合でも管理ができる | 複数の状態を管理する場合は厳しい（combine reducer使えば問題なさそう） |
| Redux | 複数の状態を管理する場合は管理しやすい | 学習コストが高い |

**Comment by soysan** [comment]
わかりやすくありがとうございます。

### 懸念点-パフォーマンスについて
| 管理法 | 内容 |
| ------ | ---- |
| State <br/> Context | 再レンダリングしまくりになる可能性もありますね。Contextも結局State, Reducerなど使用すると同じかも知れません。回避するためにmemo, callbackは必須ですね。|
| Redux | 必要なコンポーネントだけ再レンダリングする
-------------

上に検索バーをつけるって話を採用するならContextかReduxを検討しないといけないような気がします。

Reduxですが個人的にContext触ってたらすぐに理解できそうって思います。私はClass ComponentのやつしかやったことないのでFCだと違うのかも知れませんが。

**Comment by hiro-minami** [comment]
なるほど、承知しました。
Redux全く触ったことないのでキャッチアップからですがやってみます。

**Comment by soysan** [comment]
お時間と相談で大丈夫です。
工数かかってしまうので、一度Stateで実装して様子見でも個人的には良いと思います。
私もあやふやなところが多いので、しっかりとこっちの方がいいと言えないので。
